name: Cypress Test
on: [push]
jobs:
  cypress-run:
      runs-on: macos-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2.4.0
        - name: Cypress.io
          uses: cypress-io/github-action@v2.9.7
          with:
            start: npx cypress run --browser chrome --env allure=true
        
