name: Cypress Test
on: [push]
jobs:
  cypress-run:
      runs-on: macos-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2.4.0
        - name: Cypress.io
          uses: cypress-io/github-action@v2.9.7
          with:
            start: npx cypress run --spec cypress/integration/LoginTest.js --record --key 463cad54-db42-4988-b5fc-4336947ba290
        
